apiVersion: apps/v1
kind: Deployment
metadata:
  name: landing-web
  namespace: production
  labels:
    name: landing-web
spec:
  replicas: 3
  selector:
    matchLabels:
      name: landing-web
  template:
    metadata:
      name: landing-web
      labels:
        name: landing-web
    spec:
      containers:
        - name: pesbuk-web
          image: indragiri21/landing-bigpro:buildNumber
          ports:
            - containerPort: 80
